// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7h5lwm7lOC4mWUJ0l0-E1t0togVF6Fo',
    appId: '1:543268034536:android:f549d2233ee5710268f65d',
    messagingSenderId: '543268034536',
    projectId: 'fir-test-29cf9',
    databaseURL: 'https://fir-test-29cf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-29cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWoJcCTJ_C_9BU6jBGC0ssUgMeWzcEas',
    appId: '1:543268034536:ios:2ddb79a728892d2968f65d',
    messagingSenderId: '543268034536',
    projectId: 'fir-test-29cf9',
    databaseURL: 'https://fir-test-29cf9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-29cf9.appspot.com',
    iosClientId: '543268034536-2b5hpr1buhhohtb5v71kft2tpthbadaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstReleaseApp',
  );
}
